version: '3'

services:
  guacd:
    image: guacamole/guacd:1.3.0
    restart: always
    volumes:
      - guacd-drive:/drive:rw
      - guacd-record:/record:rw

  postgres:
    image: postgres:13
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    ports:
      #      - 5432/tcp
      - 5432:5432/tcp # TODO only for debugging
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data:rw

  guacamole:
    image: guacamole/guacamole:1.3.0
    restart: always
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    depends_on:
      - guacd
      - postgres
    links:
      - guacd
    ports:
      - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.

  tigers:
    image: robocupssl/ubuntu-vnc:latest
    build:
      context: src/ubuntu
    restart: always
    volumes:
      - tigers-data:/home/default:rw
    ports:
      - 5901/tcp

  erforce:
    image: robocupssl/ubuntu-vnc:latest
    build:
      context: src/ubuntu
    restart: always
    volumes:
      - erforce-data:/home/default:rw
    ports:
      - 5901/tcp

  nginx:
    image: nginx:1.19
    volumes:
      - ./init/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80/tcp
      - 443:443/tcp

volumes:
  guacd-drive:
  guacd-record:
  postgres-data:
  tigers-data:
  erforce-data:
