version: '2.4'

services:
  guacd:
    image: guacamole/guacd:1.3.0
    restart: unless-stopped
    mem_limit: 50m
    cpus: 1
    volumes:
      - guacd-drive:/drive:rw
      - guacd-record:/record:rw
    networks:
      - guacamole
      - match

  postgres:
    image: postgres:13
    restart: unless-stopped
    mem_limit: 200m
    cpus: 0.5
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD:
      POSTGRES_USER: guacamole_user
    ports:
      - 5432/tcp
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - guacamole

  guacamole:
    image: guacamole/guacamole:1.3.0
    restart: unless-stopped
    mem_limit: 1g
    cpus: 1
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD:
      POSTGRES_USER: guacamole_user
    depends_on:
      - guacd
      - postgres
    ports:
      - 8080/tcp # Guacamole is on :8080/guacamole, not /.
    networks:
      guacamole:
      expose:
        aliases:
          - "guacamole.${COMPOSE_PROJECT_NAME}"

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:1.5.0
    command: [ "-visionAddress", "224.5.23.2:10006" ]
    restart: unless-stopped
    mem_limit: 50m
    cpus: 0.5
    ports:
      - 8082/tcp
    networks:
      match:
      expose:
        aliases:
          - "ssl-vision-client.${COMPOSE_PROJECT_NAME}"

  ssl-status-board:
    image: robocupssl/ssl-status-board:2.1.1
    restart: unless-stopped
    mem_limit: 50m
    cpus: 0.5
    ports:
      - 8082/tcp
    networks:
      match:
      expose:
        aliases:
          - "ssl-status-board.${COMPOSE_PROJECT_NAME}"

  ssl-game-controller-private:
    image: robocupssl/ssl-game-controller:2.6.3
    command:
      - "-visionAddress"
      - "224.5.23.2:11006"
      - "-trackerAddress"
      - "224.5.23.2:11010"
      - "-publishAddress"
      - "224.5.23.1:11003"
      - "-address"
      - ":8081"
    restart: unless-stopped
    mem_limit: 50m
    cpus: 0.5
    volumes:
      - game-controller-config:/config:rw
    ports:
      - 8081/tcp
    networks:
      referee:
      expose:
        aliases:
          - "ssl-game-controller-private.${COMPOSE_PROJECT_NAME}"

  ssl-game-controller-public:
    image: g3force/proxy-tcp-udp-mc:0.1.1
    command:
      - "tcp,:10007,ssl-game-controller-private:10007,AutoRef"
      - "tcp,:10008,ssl-game-controller-private:10008,Team"
      - "tcp,:10011,ssl-game-controller-private:10011,RemoteCtrl"
      - "mc,224.5.23.1:11003,224.5.23.1:10003,Referee"
      - "mc,224.5.23.2:10006,224.5.23.2:11006,Vision"
      - "mc,224.5.23.2:10010,224.5.23.2:11010,Tracker"
    restart: unless-stopped
    mem_limit: 50m
    cpus: 0.1
    ports:
      - 10007/tcp
      - 10008/tcp
      - 10011/tcp
    networks:
      referee:
      match:

#  grsim:
#    image: robocupssl/grsim:2.4.0
#    restart: unless-stopped
#    mem_limit: 50m
#    cpus: 1
#    environment:
#      - VNC_PASSWORD=${VNC_PW}
#    ports:
#      - 10300/udp
#      - 10301/udp
#      - 10302/udp
#    networks:
#      - simulator

  erforce-sim:
    image: roboticserlangen/simulatorcli:commit-25d461a81d6f
    restart: unless-stopped
    mem_limit: 50m
    cpus: 1
    ports:
      - 10300/udp
      - 10301/udp
      - 10302/udp
    networks:
      - simulator

  simulator:
    image: g3force/proxy-tcp-udp-mc:0.1.1
    command:
      - "udp,:10301,erforce-sim:10301,Blue"
      - "udp,:10302,erforce-sim:10302,Yellow"
      - "mc,224.5.23.2:10020,224.5.23.2:10006,Vision"
      - "mc,224.5.23.1:10003,224.5.23.1:11003,Referee"
      - "mc,224.5.23.2:10010,224.5.23.2:11010,Tracker"
    restart: unless-stopped
    mem_limit: 50m
    cpus: 0.1
    ports:
      - 10300/udp
      - 10301/udp
      - 10302/udp
    networks:
      - simulator
      - match

  ssl-simulation-controller:
    image: robocupssl/ssl-simulation-controller:0.5.2
    command:
      - "-refereeAddress"
      - "224.5.23.1:11003"
      - "-visionAddress"
      - "224.5.23.2:10020"
      - "-trackerAddress"
      - "224.5.23.2:11010"
      - "-simControlPort"
      - "10300"
      - "-robotSpecConfig"
      - "/config/robot-specs.yaml"
    restart: unless-stopped
    mem_limit: 50m
    cpus: 0.1
    volumes:
      - ./config/ssl-simulation-controller:/config:ro
    networks:
      - simulator

  # Maintainer is a container for the maintainers of the event for testing purposes
  maintainer:
    image: robocupssl/ubuntu-vnc-go:0.2.0
    restart: unless-stopped
    mem_limit: 500m
    cpus: 1
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - maintainer-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  autoref-tigers:
    image: tigersmannheim/auto-referee-vnc:0.9.7
    # Run with UI (note: need to connect to the UI once to start the autoRef)
    # command: [ "vnc", "-a" ]
    # Run without UI in active mode
    command: [ "-a" ]
    restart: unless-stopped
    mem_limit: 2g
    cpus: 2
    environment:
      - VNC_PASSWORD=${VNC_PW}
    ports:
      - 5900/tcp
    networks:
      - match
      - guacamole

  team-tigers:
    image: robocupssl/ubuntu-vnc-java:0.2.0
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-tigers-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

  team-erforce:
    image: roboticserlangen/robocup:latest
    restart: unless-stopped
    mem_limit: "${TEAM_LIMIT_MEM}"
    cpus: "${TEAM_LIMIT_CPU}"
    environment:
      SSH_PUBLIC_KEY:
      VNC_PW:
    volumes:
      - team-erforce-data:/home/default:rw
    ports:
      - 5901/tcp
      - 2222/tcp
    networks:
      - match
      - guacamole

volumes:
  guacd-drive:
  guacd-record:
  postgres-data:
  game-controller-config:
  maintainer-data:
  team-tigers-data:
    external: true
  team-erforce-data:
    external: true

networks:
  expose:
  match:
  simulator:
  referee:
  guacamole:
