version: '3'

services:
  guacd:
    image: guacamole/guacd:1.3.0
    restart: always
    mem_limit: 50m
    cpus: 1
    volumes:
      - guacd-drive:/drive:rw
      - guacd-record:/record:rw
    networks:
      - mgmt
      - match

  postgres:
    image: postgres:13
    restart: always
    mem_limit: 200m
    cpus: 0.5
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    ports:
      - 5432/tcp
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - mgmt

  guacamole:
    image: guacamole/guacamole:1.3.0
    restart: always
    mem_limit: 1g
    cpus: 1
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    depends_on:
      - guacd
      - postgres
    links:
      - guacd
    ports:
      - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
    networks:
      - mgmt

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:1.2.0
    command: [ "-visionAddress", "224.5.23.2:10006" ]
    restart: always
    mem_limit: 50m
    cpus: 0.5
    ports:
      - 8081:8082/tcp
    networks:
      - match

  ssl-status-board:
    image: robocupssl/ssl-status-board:2.1.0
    restart: always
    mem_limit: 50m
    cpus: 0.5
    ports:
      - 8082:8082/tcp
    networks:
      - match

  ssl-game-controller:
    image: robocupssl/ssl-game-controller:2.5.1
    command: [ "-visionAddress", "224.5.23.2:10006", "-address", ":8081" ]
    restart: always
    mem_limit: 50m
    cpus: 0.5
    volumes:
      - game-controller-config:/config:rw
    ports:
      - 8083:8081/tcp
    networks:
      - match

  grsim:
    image: robocupssl/grsim:latest
    restart: always
    mem_limit: 50m
    cpus: 1
    ports:
      - 10300/udp
      - 10301/udp
      - 10302/udp
    networks:
      - simulator

  simulator:
    image: ssl-simulation-proxy
    command:
      - "udp;:10300;grsim:10300"
      - "udp;:10301;grsim:10301"
      - "udp;:10302;grsim:10302"
      - "mc;224.5.23.2:10020;224.5.23.2:10006"
    restart: always
    mem_limit: 50m
    cpus: 0.1
    ports:
      - 10300/udp
      - 10301/udp
      - 10302/udp
    networks:
      - simulator
      - match

  tigers:
    image: robocupssl/ubuntu-vnc-java:latest
    restart: always
    mem_limit: 2g
    cpus: 2
    volumes:
      - tigers-data:/home/default:rw
    ports:
      - 5901/tcp
    networks:
      - match

  erforce:
    image: robocupssl/ubuntu-vnc:latest
    restart: always
    mem_limit: 2g
    cpus: 2
    volumes:
      - erforce-data:/home/default:rw
    ports:
      - 5901/tcp
    networks:
      - match

  nginx:
    image: nginx:1.19
    restart: always
    mem_limit: 50m
    cpus: 0.5
    volumes:
      - ./init/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - mgmt
      - match

volumes:
  guacd-drive:
  guacd-record:
  postgres-data:
  game-controller-config:
  tigers-data:
  erforce-data:

networks:
  mgmt:
  match:
  simulator:
