version: '3'

services:
  guacd:
    image: guacamole/guacd:1.3.0
    restart: always
    mem_limit: 50m
    cpus: 1
    volumes:
      - guacd-drive:/drive:rw
      - guacd-record:/record:rw
    networks:
      - guacamole
      - match

  postgres:
    image: postgres:13
    restart: always
    mem_limit: 200m
    cpus: 0.5
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    ports:
      - 5432/tcp
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data:rw
    networks:
      - guacamole

  guacamole:
    image: guacamole/guacamole:1.3.0
    restart: always
    mem_limit: 1g
    cpus: 1
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    depends_on:
      - guacd
      - postgres
    ports:
      - 8080/tcp # Guacamole is on :8080/guacamole, not /.
    networks:
      guacamole:
      expose:
          aliases:
            - "guacamole.${COMPOSE_PROJECT_NAME}"

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:1.2.0
    command: [ "-visionAddress", "224.5.23.2:10006" ]
    restart: always
    mem_limit: 50m
    cpus: 0.5
    ports:
      - 8082/tcp
    networks:
      match:
      expose:
        aliases:
          - "ssl-vision-client.${COMPOSE_PROJECT_NAME}"

  ssl-status-board:
    image: robocupssl/ssl-status-board:2.1.0
    restart: always
    mem_limit: 50m
    cpus: 0.5
    ports:
      - 8082/tcp
    networks:
      match:
      expose:
        aliases:
          - "ssl-status-board.${COMPOSE_PROJECT_NAME}"

  ssl-game-controller-private:
    image: robocupssl/ssl-game-controller:2.6.0
    command:
      - "-visionAddress"
      - "224.5.23.2:11006"
      - "-trackerAddress"
      - "224.5.23.2:11010"
      - "-publishAddress"
      - "224.5.23.1:11003"
      - "-address"
      - ":8081"
    restart: always
    mem_limit: 50m
    cpus: 0.5
    volumes:
      - game-controller-config:/config:rw
    ports:
      - 8081/tcp
    networks:
      referee:
      expose:
        aliases:
          - "ssl-game-controller-private.${COMPOSE_PROJECT_NAME}"

  ssl-game-controller-public:
    image: g3force/proxy-tcp-udp-mc:0.1.0
    command:
      - "tcp,:10007,ssl-game-controller-private:10007,AutoRef"
      - "tcp,:10008,ssl-game-controller-private:10008,Team"
      - "tcp,:10011,ssl-game-controller-private:10011,RemoteCtrl"
      - "mc,224.5.23.1:11003,224.5.23.1:10003,Referee"
      - "mc,224.5.23.2:10006,224.5.23.2:11006,Vision"
      - "mc,224.5.23.2:10010,224.5.23.2:11010,Tracker"
    restart: always
    mem_limit: 50m
    cpus: 0.1
    ports:
      - 10007/tcp
      - 10008/tcp
      - 10011/tcp
    networks:
      referee:
      match:

  grsim:
    image: robocupssl/grsim:latest
    restart: always
    mem_limit: 50m
    cpus: 1
    ports:
      - 10300/udp
      - 10301/udp
      - 10302/udp
    networks:
      - simulator

  simulator:
    image: g3force/proxy-tcp-udp-mc:0.1.0
    command:
      - "udp,:10300,grsim:10300,Control"
      - "udp,:10301,grsim:10301,Blue"
      - "udp,:10302,grsim:10302,Yellow"
      - "mc,224.5.23.2:10020,224.5.23.2:10006,Vision"
    restart: always
    mem_limit: 50m
    cpus: 0.1
    ports:
      - 10300/udp
      - 10301/udp
      - 10302/udp
    networks:
      - simulator
      - match

  tigers:
    image: robocupssl/ubuntu-vnc-java:latest
    restart: always
    mem_limit: 2g
    cpus: 2
    volumes:
      - tigers-data:/home/default:rw
    ports:
      - 5901/tcp
    networks:
      - match
      - guacamole

  erforce:
    image: robocupssl/ubuntu-vnc:latest
    restart: always
    mem_limit: 2g
    cpus: 2
    volumes:
      - erforce-data:/home/default:rw
    ports:
      - 5901/tcp
    networks:
      - match
      - guacamole

volumes:
  guacd-drive:
  guacd-record:
  postgres-data:
  game-controller-config:
  tigers-data:
  erforce-data:

networks:
  expose:
  match:
  simulator:
  referee:
  guacamole:
